name: make and check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd src && echo 'cc -Xlinker -x' >conf-ld && sed -ie 's/ -static//' Makefile && make
    - name: check
      run: cd src && make check
